### ISSUE TITLE
Error (canvas)? unable to "lite up" or "make up"

### ISSUE THREAD

**Issue by heryoff** [wtfnotavailable/Discord-MusicBot#112]
I'm on arm, might be the issue?
Getting this error:

```
    OS: Linux
    ARCHITECURE: aarch64
    PROJECT_NAME: discord-musicbot
    PROJECT_PATH: /home/ubuntu/DOCKERS/musicbot/Discord-MusicBot

WARN[0000] The "JWT_SECRET_KEY" variable is not set. Defaulting to a blank string. 
WARN[0000] The "JWT_SECRET_KEY" variable is not set. Defaulting to a blank string. 

> discord-musicbot@5.2.1-beta start
> npm i && npm run bot

npm ERR! code 1
npm ERR! path /home/ubuntu/DOCKERS/musicbot/Discord-MusicBot/djs-bot/node_modules/canvas
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary
npm ERR! Failed to execute '/root/.nvm/versions/node/v20.8.0/bin/node /root/.nvm/versions/node/v20.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/home/ubuntu/DOCKERS/musicbot/Discord-MusicBot/djs-bot/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/ubuntu/DOCKERS/musicbot/Discord-MusicBot/djs-bot/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
npm ERR! node-pre-gyp info using node@20.8.0 | linux | arm64
npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-glibc-arm64.tar.gz
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-glibc-arm64.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@20.8.0 (node-v115 ABI, glibc) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v115-linux-glibc-arm64.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@20.8.0 | linux | arm64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@20.8.0 | linux | arm64
npm ERR! gyp info find Python using Python version 3.10.12 found at "/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v20.8.0/node-v20.8.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v20.8.0/node-v20.8.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v20.8.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v20.8.0/SHASUMS256.txt
npm ERR! gyp info spawn /usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/root/.nvm/versions/node/v20.8.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/home/ubuntu/DOCKERS/musicbot/Discord-MusicBot/djs-bot/node_modules/canvas/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.nvm/versions/node/v20.8.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/root/.cache/node-gyp/20.8.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/20.8.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/root/.nvm/versions/node/v20.8.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/20.8.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/DOCKERS/musicbot/Discord-MusicBot/djs-bot/node_modules/canvas',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! /bin/sh: 1: pkg-config: not found
npm ERR! gyp: Call to 'pkg-config pixman-1 --libs' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/root/.nvm/versions/node/v20.8.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Linux 5.15.0-1040-oracle
npm ERR! gyp ERR! command "/root/.nvm/versions/node/v20.8.0/bin/node" "/root/.nvm/versions/node/v20.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/home/ubuntu/DOCKERS/musicbot/Discord-MusicBot/djs-bot/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/home/ubuntu/DOCKERS/musicbot/Discord-MusicBot/djs-bot/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v115"
npm ERR! gyp ERR! cwd /home/ubuntu/DOCKERS/musicbot/Discord-MusicBot/djs-bot/node_modules/canvas
npm ERR! gyp ERR! node -v v20.8.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/root/.nvm/versions/node/v20.8.0/bin/node /root/.nvm/versions/node/v20.8.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/home/ubuntu/DOCKERS/musicbot/Discord-MusicBot/djs-bot/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/home/ubuntu/DOCKERS/musicbot/Discord-MusicBot/djs-bot/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v115' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/ubuntu/DOCKERS/musicbot/Discord-MusicBot/djs-bot/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:514:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1105:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
npm ERR! node-pre-gyp ERR! System Linux 5.15.0-1040-oracle
npm ERR! node-pre-gyp ERR! command "/root/.nvm/versions/node/v20.8.0/bin/node" "/home/ubuntu/DOCKERS/musicbot/Discord-MusicBot/djs-bot/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
npm ERR! node-pre-gyp ERR! cwd /home/ubuntu/DOCKERS/musicbot/Discord-MusicBot/djs-bot/node_modules/canvas
npm ERR! node-pre-gyp ERR! node -v v20.8.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-10-01T13_06_04_924Z-debug-0.log
Exiting gracefully with code 130
make: *** [Makefile:27: lite] Error 130
```

**Comment by LewdHuTao** [comment]
try downgrade your node version to 17.x or 18.x

**Comment by heryoff** [comment]
> try downgrade your node version to 17.x or 18.x

Still same results, node:17 and node:18. Using docker

```
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
,npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
,npm ERR! node-pre-gyp ERR! System Linux 5.15.0-1040-oracle
,npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/djs-bot/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
,npm ERR! node-pre-gyp ERR! cwd /djs-bot/node_modules/canvas
,npm ERR! node-pre-gyp ERR! node -v v18.18.0
,npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
,npm ERR! node-pre-gyp ERR! not ok
,
,npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-10-01T17_08_16_592Z-debug-0.log
,npm notice 
,npm notice New major version of npm available! 9.8.1 -> 10.1.0
,npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.1.0
,npm notice Run npm install -g npm@10.1.0 to update!
,npm notice 
,
,> discord-musicbot@5.2.1-beta start
,> npm i && npm run bot
,
,[..................] | idealTree:djs-bot: sill idealTree buildDeps
[..................] | idealTree:djs-bot: sill idealTree buildDeps
[..................] - idealTree:djs-bot: sill idealTree buildDeps
[..................] | idealTree:djs-bot: sill idealTree buildDeps
[..................] - idealTree:djs-bot: sill idealTree buildDeps
[..................] - idealTree:djs-bot: sill idealTree buildDeps
[..................] | idealTree:djs-bot: sill idealTree buildDeps
[..................] / idealTree:djs-bot: sill idealTree buildDeps
[..................] / idealTree:djs-bot: sill idealTree buildDeps
[..................] | idealTree:djs-bot: sill idealTree buildDeps
[#########.........] / idealTree:djs-bot: timing idealTree:#root Completed in 1
[#########.........] | idealTree:discord.js: sill placeDep ROOT undici@5.25.3 O
[#########.........] / idealTree:discord.js: sill placeDep ROOT undici@5.25.3 O
[#########.........] - idealTree:discord.js: sill placeDep ROOT undici@5.25.3 O
[#########.........] | idealTree:discord.js: timing idealTree:node_modules/disc
[#########.........] | idealTree:discord.js: timing idealTree:node_modules/disc
[#########.........] - idealTree:send: sill placeDep ROOT ms@2.0.0 OK for: debu
[#########.........] - idealTree:send: sill placeDep ROOT ms@2.0.0 OK for: debu
[#########.........] \ idealTree:send: sill placeDep ROOT ms@2.0.0 OK for: debu
[#######...........] / idealTree:jsonwebtoken: timing idealTree:node_modules/js
[#######...........] - idealTree:winston: sill placeDep ROOT readable-stream@4.
[#######...........] / idealTree:send: timing idealTree:node_modules/send Compl
[#######...........] / idealTree:send: timing idealTree:node_modules/send Compl
[#######...........] / idealTree:send: timing idealTree:node_modules/send Compl
[#######...........] | idealTree:send: timing idealTree:node_modules/send Compl
[#######...........] - idealTree:send: timing idealTree:node_modules/send Compl
[#######...........] - idealTree:send: timing idealTree:node_modules/send Compl
[#######...........] \ idealTree:send: timing idealTree:node_modules/send Compl
[#######...........] / idealTree:send: timing idealTree:node_modules/send Compl
[#######...........] - idealTree:send: timing idealTree:node_modules/send Compl
[#######...........] / idealTree:pixelmatch: sill placeDep ROOT pngjs@6.0.0 OK
[#######...........] - idealTree:pixelmatch: sill placeDep ROOT pngjs@6.0.0 OK
[#######...........] | idealTree:pixelmatch: timing idealTree:node_modules/pixe
[########..........] - idealTree:fs-minipass: timing idealTree:node_modules/fs-
[#########.........] \ idealTree:winston: timing idealTree:node_modules/winston
[#########.........] | idealTree: timing idealTree Completed in 2842ms
[#########.........] \ reify:@fastify/cors: sill audit bulk request {
[#########.........] \ reify:@fastify/cors: sill audit bulk request {
[#########.........] \ reify:@fastify/cors: sill audit bulk request {
[#########.........] \ reify:@fastify/cors: sill audit bulk request {
[#########.........] \ reify:@fastify/cors: sill audit bulk request {
[#########.........] \ reify:@fastify/cors: sill audit bulk request {
[#########.........] \ reify:@fastify/cors: sill audit bulk request {
[#########.........] \ reify:@fastify/cors: sill audit bulk request {
[#########.........] | reify:parse-bmfont-ascii: timing metavuln:packument:xml2
[##########........] | reify:require-from-string: timing reifyNode:node_modules
[###########.......] / reify:path-to-regexp: timing reifyNode:node_modules/colo
[############......] / reify:safe-buffer: timing reifyNode:node_modules/global
[#############.....] \ reify:proxy-from-env: timing reifyNode:node_modules/mini
[##############....] - reify:@discordjs/util: timing reifyNode:node_modules/mim
[###############...] \ reify:json-schema-traverse: timing reifyNode:node_module
[###############...] | reify:@dabh/diagnostics: timing reifyNode:node_modules/@
[################..] - reify:youtube-sr: timing reifyNode:node_modules/ws Compl
[################..] / reify:cheerio-select: timing reifyNode:node_modules/fast
[################..] / reify:ts-mixer: timing reifyNode:node_modules/busboy Com
[################..] \ reify:@jimp/plugin-resize: timing reifyNode:node_modules
[#################.] - reify:exif-parser: timing reify:audit Completed in 2055m
[#################.] \ reify:@discordjs/ws: timing reifyNode:node_modules/@mapb
[#################.] - reify:@jimp/plugin-blit: timing reifyNode:node_modules/p
[#################.] - reify:@jimp/core: timing reifyNode:node_modules/uri-js C
[#################.] / reify:entities: timing reifyNode:node_modules/@jimp/tiff
[#################.] / reify:mnemonist: timing reifyNode:node_modules/fast-json
[#################.] | reify:@types/node: timing reifyNode:node_modules/@prisma
[##################] - reify:axios: timing reifyNode:node_modules/@prisma/engin
[##################] - reify:axios: timing reifyNode:node_modules/@prisma/engin
[##################] | reify:luxon: timing reifyNode:node_modules/pino Complete
[##################] / reify:@types/node: timing reifyNode:node_modules/luxon C
[##################] \ reify:gifwrap: timing reifyNode:node_modules/jimp Comple
[##################] / reify:fastify: timing reifyNode:node_modules/discord.js
[##################] - reify:ajv: timing reifyNode:node_modules/fastify Complet
[##################] - reify:ajv: timing reifyNode:node_modules/fastify Complet
[##################] | reify:prisma: timing reifyNode:node_modules/moment Compl
[##################] - reify:discord-api-types: timing reifyNode:node_modules/l
[##################] \ reify:typescript: timing reifyNode:node_modules/discord-
[##################] \ reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] | reify:typescript: timing reifyNode:node_modules/discord-
[##################] / reify:typescript: timing reifyNode:node_modules/discord-
[##################] / reify:typescript: timing reifyNode:node_modules/discord-
[##################] / reify:typescript: timing reifyNode:node_modules/discord-
[##################] / reify:typescript: timing reifyNode:node_modules/discord-
[##################] / reify:typescript: timing reifyNode:node_modules/discord-
[##################] / reify:typescript: timing reifyNode:node_modules/discord-
[##################] / reify:typescript: timing reifyNode:node_modules/discord-
[##################] / reify:typescript: timing reifyNode:node_modules/discord-
[##################] / reify:typescript: timing reifyNode:node_modules/discord-
[##################] / reify:typescript: timing reifyNode:node_modules/discord-
[##################] / reify:typescript: timing reifyNode:node_modules/discord-
[##################] / reify:typescript: timing reifyNode:node_modules/discord-

npm ERR! code 1
,npm ERR! path /djs-bot/node_modules/canvas
,npm ERR! command failed
,npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary
,npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/djs-bot/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/djs-bot/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
,npm ERR! node-pre-gyp info it worked if it ends with ok
,npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
,npm ERR! node-pre-gyp info using node@18.18.0 | linux | arm64
,npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-linux-glibc-arm64.tar.gz
,npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-linux-glibc-arm64.tar.gz 
,npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@18.18.0 (node-v108 ABI, glibc) (falling back to source compile with node-gyp) 
,npm ERR! node-pre-gyp WARN Hit error response status 404 Not Found on https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-linux-glibc-arm64.tar.gz 
,npm ERR! gyp info it worked if it ends with ok
,npm ERR! gyp info using node-gyp@9.4.0
,npm ERR! gyp info using node@18.18.0 | linux | arm64
,npm ERR! gyp info ok 
,npm ERR! gyp info it worked if it ends with ok
,npm ERR! gyp info using node-gyp@9.4.0
,npm ERR! gyp info using node@18.18.0 | linux | arm64
,npm ERR! gyp info find Python using Python version 3.11.2 found at "/usr/bin/python3"
,npm ERR! gyp info spawn /usr/bin/python3
,npm ERR! gyp info spawn args [
,npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
,npm ERR! gyp info spawn args   'binding.gyp',
,npm ERR! gyp info spawn args   '-f',
,npm ERR! gyp info spawn args   'make',
,npm ERR! gyp info spawn args   '-I',
,npm ERR! gyp info spawn args   '/djs-bot/node_modules/canvas/build/config.gypi',
,npm ERR! gyp info spawn args   '-I',
,npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
,npm ERR! gyp info spawn args   '-I',
,npm ERR! gyp info spawn args   '/root/.cache/node-gyp/18.18.0/include/node/common.gypi',
,npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
,npm ERR! gyp info spawn args   '-Dvisibility=default',
,npm ERR! gyp info spawn args   '-Dnode_root_dir=/root/.cache/node-gyp/18.18.0',
,npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
,npm ERR! gyp info spawn args   '-Dnode_lib_file=/root/.cache/node-gyp/18.18.0/<(target_arch)/node.lib',
,npm ERR! gyp info spawn args   '-Dmodule_root_dir=/djs-bot/node_modules/canvas',
,npm ERR! gyp info spawn args   '-Dnode_engine=v8',
,npm ERR! gyp info spawn args   '--depth=.',
,npm ERR! gyp info spawn args   '--no-parallel',
,npm ERR! gyp info spawn args   '--generator-output',
,npm ERR! gyp info spawn args   'build',
,npm ERR! gyp info spawn args   '-Goutput_dir=.'
,npm ERR! gyp info spawn args ]
,npm ERR! Package pangocairo was not found in the pkg-config search path.
,npm ERR! Perhaps you should add the directory containing `pangocairo.pc'
,npm ERR! to the PKG_CONFIG_PATH environment variable
,npm ERR! Package 'pangocairo', required by 'virtual:world', not found
,npm ERR! gyp: Call to 'pkg-config pangocairo --libs' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
,npm ERR! gyp ERR! configure error 
,npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
,npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:325:16)
,npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
,npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:292:12)
,npm ERR! gyp ERR! System Linux 5.15.0-1040-oracle
,npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/djs-bot/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/djs-bot/node_modules/canvas/build/Release" "--napi_version=9" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
,npm ERR! gyp ERR! cwd /djs-bot/node_modules/canvas
,npm ERR! gyp ERR! node -v v18.18.0
,npm ERR! gyp ERR! node-gyp -v v9.4.0
,npm ERR! gyp ERR! not ok 
,npm ERR! node-pre-gyp ERR! build error 
,npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/djs-bot/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/djs-bot/node_modules/canvas/build/Release --napi_version=9 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
,npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/djs-bot/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
,npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
,npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
,npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:303:5)
,npm ERR! node-pre-gyp ERR! System Linux 5.15.0-1040-oracle
,npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/djs-bot/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
,npm ERR! node-pre-gyp ERR! cwd /djs-bot/node_modules/canvas
,npm ERR! node-pre-gyp ERR! node -v v18.18.0
,npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
,npm ERR! node-pre-gyp ERR! not ok
,
,npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2023-10-01T17_09_01_566Z-debug-0.log
,
,> discord-musicbot@5.2.1-beta start
,> npm i && npm run bot
,

```

**Comment by BioCla** [comment]
this seems to be a problem with the standalone api building process. try running it through the development environment and make sure to have set the correct environment variables for the docker config

**Comment by jcbertoli** [comment]
[This](https://github.com/Automattic/node-canvas/wiki/Installation%3A-Ubuntu-and-other-Debian-based-systems)  solved the issue for me. Just had to run it in 'djs-bot' container
