### ISSUE TITLE
SUSPICIOUS - Could not load track.

### ISSUE THREAD

**Issue by DelgshSeli** [wtfnotavailable/Discord-MusicBot#208]
![image](https://github.com/wtfnotavailable/Discord-MusicBot/assets/96995162/40f0e297-2c9a-41a9-8c20-d972d8e2eaac)

**Comment by xkraze11** [comment]
Same here. It fixed itself once, then happened again 24h later. Restart fixed it the next time. Could this be some YouTube token not renewing in time? Here are my logs:

```
djs-bot            | [18.02.2024 - 10:51] [WARN ] | Player: xxxxxxxxxxxxxxxx | A music player has been created in xxxxxx
lavalink           | 2024-02-18 10:51:50.856  INFO 1 --- [   XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op":"volume","guildId":"xxxxxxxxxxxxxxxx","volume":100}
lavalink           | 2024-02-18 10:51:51.122  INFO 1 --- [   XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op":"voiceUpdate","guildId":"xxxxxxxxxxxxxxxx","sessionId":"xxxxxxxxxxxxxxxx","event":{"token":"xxxxxxxxxxxxxxxx","guild_id":"xxxxxxxxxxxxxxxx","endpoint":"xxxxxxxxxxxxxxxx"}}
lavalink           | 2024-02-18 10:51:51.350  INFO 1 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/watch?v=xxxxxxxxxxxxxxxx"
lavalink           | 2024-02-18 10:51:51.462 ERROR 1 --- [ader-2-thread-1] c.s.d.l.p.DefaultAudioPlayerManager      : Error in loading item https://www.youtube.com/watch?v=xxxxxxxxxxxxxxxx
lavalink           |
lavalink           | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for a YouTube track failed.
lavalink           |    at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:242) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:254) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:250) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:102) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:67) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:45) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:218) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:149) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:406) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:388) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:183) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
lavalink           |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
lavalink           |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
lavalink           |    at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
lavalink           |    Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
lavalink           |   lavaplayer.version: 1.5.2
lavalink           |   os.arch: amd64
lavalink           |   os.name: Linux
lavalink           |   os.version: 5.10.0-26-amd64
lavalink           |   java.vendor: Eclipse Adoptium
lavalink           |   java.version: 18.0.2.1
lavalink           |   java.runtime.version: 18.0.2.1+1
lavalink           |   java.vm.version: 18.0.2.1+1
lavalink           | Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for video page response: 400
lavalink           |    at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.toRuntimeException(ExceptionTools.java:67) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:38) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:230) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    ... 14 common frames omitted
lavalink           | Caused by: java.io.IOException: Invalid status code for video page response: 400
lavalink           |    at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:154) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:240) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:48) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:36) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    ... 15 common frames omitted
lavalink           |
lavalink           | 2024-02-18 10:51:51.464 ERROR 1 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed
lavalink           |
lavalink           | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Loading information for a YouTube track failed.
lavalink           |    at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:242) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:254) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:250) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:102) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:67) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:45) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:218) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:149) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:406) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:388) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:183) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
lavalink           |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
lavalink           |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
lavalink           |    at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
lavalink           |    Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
lavalink           |   lavaplayer.version: 1.5.2
lavalink           |   os.arch: amd64
lavalink           |   os.name: Linux
lavalink           |   os.version: 5.10.0-26-amd64
lavalink           |   java.vendor: Eclipse Adoptium
lavalink           |   java.version: 18.0.2.1
lavalink           |   java.runtime.version: 18.0.2.1+1
lavalink           |   java.vm.version: 18.0.2.1+1
lavalink           | Caused by: java.lang.RuntimeException: java.io.IOException: Invalid status code for video page response: 400
lavalink           |    at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.toRuntimeException(ExceptionTools.java:67) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:38) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:230) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    ... 14 common frames omitted
lavalink           | Caused by: java.io.IOException: Invalid status code for video page response: 400
lavalink           |    at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:154) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadTrackInfoFromInnertube(DefaultYoutubeTrackDetailsLoader.java:240) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:48) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:36) ~[lavaplayer-1.5.2.jar!/:na]
lavalink           |    ... 15 common frames omitted
lavalink           |
lavalink           | 2024-02-18 10:51:51.467  INFO 1 --- [  XNIO-1 task-1] lavalink.server.io.RequestLoggingFilter  : GET /loadtracks?identifier=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%xxxxxxxxxxxxxxxx, client=xxxxxxxxxxxxxxxx
lavalink           | 2024-02-18 10:51:51.468  INFO 1 --- [   XNIO-1 I/O-4] lavalink.server.io.SocketServer          : {"op":"destroy","guildId":"xxxxxxxxxxxxxxxx"}
```

**Comment by DlgshKurd** [comment]
the worse part is the bot get disconnected and all the queue get deleted, I would suggest the developers to fix it by playing the next track instead of just kicking it out of the vc. 

I tried to fix it. but I failed XD

**Comment by SuspiciousLookingOwl** [comment]
I'm using Lavalink v3 too on my project and facing a similar issue, I made my own fork and ran the workflow so it uses the snapshot version of Lavaplayer that contains the fixes. Can't confirm yet that it actually solves the issues.

https://github.com/SuspiciousLookingOwl/Lavalink/actions/runs/8035035875 (download artifacts)

**Comment by xkraze11** [comment]
A day after my comment a new lavalink branch was made implementing the fix and I haven't gotten the error since switching to it. If you're using docker you can just switch from lavalink:3 -> lavalink:fix-yt-400-v3 in the docker-compose.yml and you're set!

**Comment by tylerrun1** [comment]
> I'm using Lavalink v3 too on my project and facing a similar issue, I made my own fork and ran the workflow so it uses the snapshot version of Lavaplayer that contains the fixes. Can't confirm yet that it actually solves the issues.
> 
> https://github.com/SuspiciousLookingOwl/Lavalink/actions/runs/8035035875 (download artifacts)
> 
> EDIT: 24 hours later, haven't faced the same 400 issue since I used my build, so seems like it does fix the issue

I'm using your lavalink v3 fork one and it has been running thoroughly. Thanks a lot!

**Comment by DarrenOfficial** [comment]
For future reference https://github.com/wtfnotavailable/Discord-MusicBot/issues/229#issuecomment-2046547862
