### ISSUE TITLE
Cannot play music "There was an error while searching"

### ISSUE THREAD

**Issue by Netamaru** [wtfnotavailable/Discord-MusicBot#223]
I've tried other versions of Lavalink and still facing the same issue.
Currently using lavalink:fix-yt-400-v3
```
lavalink   | 2024-03-29 11:36:16.710  INFO 1 --- [  XNIO-1 task-1] l.server.player.AudioLoaderRestHandler   : Got request to load for identifier "https://www.youtube.com/watch?v=xAz_DzPUjrM"
lavalink   | 2024-03-29 11:36:16.757 ERROR 1 --- [ader-2-thread-1] lavalink.server.player.AudioLoader       : Load failed
lavalink   |
lavalink   | com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Video returned by YouTube isn't what was requested
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.load(DefaultYoutubeTrackDetailsLoader.java:59) ~[lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeTrackDetailsLoader.loadDetails(DefaultYoutubeTrackDetailsLoader.java:36) ~[lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadTrackWithVideoId(YoutubeAudioSourceManager.java:230) ~[lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:254) ~[lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager$LoadingRoutes.track(YoutubeAudioSourceManager.java:250) ~[lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromUrlWithVideoId(DefaultYoutubeLinkRouter.java:103) ~[lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.routeFromMainDomain(DefaultYoutubeLinkRouter.java:68) ~[lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.DefaultYoutubeLinkRouter.route(DefaultYoutubeLinkRouter.java:46) ~[lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItemOnce(YoutubeAudioSourceManager.java:218) ~[lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioSourceManager.loadItem(YoutubeAudioSourceManager.java:149) ~[lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:406) ~[lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:388) ~[lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT.jar!/:na]
lavalink   |    at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:183) ~[lavaplayer-6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT.jar!/:na]
lavalink   |    at java.base/java.util.concurrent.FutureTask.run(Unknown Source) ~[na:na]
lavalink   |    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
lavalink   |    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
lavalink   |    at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
lavalink   |    Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
lavalink   |   lavaplayer.version: 6d14c5b2d96fd953c671cfae8f9b9ea11aa20d5a-SNAPSHOT
lavalink   |   os.arch: amd64
lavalink   |   os.name: Linux
lavalink   |   os.version: 5.15.0-100-generic
lavalink   |   java.vendor: Eclipse Adoptium
lavalink   |   java.version: 18.0.2.1
lavalink   |   java.runtime.version: 18.0.2.1+1
lavalink   |   java.vm.version: 18.0.2.1+1
lavalink   | Caused by: java.lang.IllegalStateException:
```

Full log: 
[lavalink-2024-03-29 113616.710.log](https://github.com/wtfnotavailable/Discord-MusicBot/files/14803816/lavalink-2024-03-29.113616.710.log)

**Comment by berithpy** [comment]
I ran into a similar issue and found that other projects using lavalink were running into the same issue https://github.com/lavalink-devs/Lavalink/issues/1030

**Comment by LewdHuTao** [comment]
This jar should fix the issue: https://serux.pro/Lavalink-v3-403-retry.jar

**Comment by FuLygon** [comment]
updating lavalink to `fredboat/lavalink:v3-update-lp-alpine` image should fix it

**Comment by RJ1002** [comment]
> This jar should fix the issue: https://serux.pro/Lavalink-v3-403-retry.jar

Thank you! That fixed it. it also fixed the playlist issue.

**Comment by Netamaru** [comment]
Thanks, no issues after 24 hours
