### ISSUE TITLE
[ERROR] | [FATAL] Possibly Unhandled Rejection

### ISSUE THREAD

**Issue by szentigrad3** [wtfnotavailable/Discord-MusicBot#72]
Got this error when the song started playing on the newest git update
djs-bot    | [24:7:2023 - 13:43] [ERROR] | [FATAL] Possibly Unhandled Rejection
djs-bot    |    Reason: TypeError: Cannot read properties of undefined (reading 'send')
djs-bot    |
djs-bot    | Promise {
djs-bot    |   <rejected> TypeError: Cannot read properties of undefined (reading 'send')
djs-bot    |       at /djs-bot/util/controlChannel.js:315:4
djs-bot    |       at runIfNotControlChannel (/djs-bot/util/controlChannel.js:299:10)
djs-bot    |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
djs-bot    | }

**Comment by BioCla** [comment]
Could please try from a clean clone and try again?
If the same thing happens please report the whole log for the session of the bot (Obfuscate your bot ID and sensitive info)
Also please try to explain exactly what you were doing in the moment which the error was produced

**Comment by szentigrad3** [comment]
got a new error while trying to npm run deploy

noidea@scorpio-brain:~/Discord-MusicBot/djs-bot$ npm run deploy

> discord-musicbot@5.2.1-beta deploy
> node scripts/global

node:internal/modules/cjs/loader:1042
  throw err;
  ^

Error: Cannot find module '../api/v1/dist'
Require stack:
- /home/noidea/Discord-MusicBot/djs-bot/lib/Bot.js
- /home/noidea/Discord-MusicBot/djs-bot/scripts/global.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1039:15)
    at Module._load (node:internal/modules/cjs/loader:885:27)
    at Module.require (node:internal/modules/cjs/loader:1105:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/home/noidea/Discord-MusicBot/djs-bot/lib/Bot.js:7:17)
    at Module._compile (node:internal/modules/cjs/loader:1218:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1272:10)
    at Module.load (node:internal/modules/cjs/loader:1081:32)
    at Module._load (node:internal/modules/cjs/loader:922:12)
    at Module.require (node:internal/modules/cjs/loader:1105:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/noidea/Discord-MusicBot/djs-bot/lib/Bot.js',
    '/home/noidea/Discord-MusicBot/djs-bot/scripts/global.js'
  ]
}

Node.js v18.13.0
noidea@scorpio-brain:~/Discord-MusicBot/djs-bot$

**Comment by BioCla** [comment]
run it with the make commands please

**Comment by szentigrad3** [comment]
ran from a clean clone and all seems to be fine
