### ISSUE TITLE
Error: connect ETIMEDOUT 2606:4700:3036::ac43:b2c7:2333

### ISSUE THREAD

**Issue by voaii** [wtfnotavailable/Discord-MusicBot#81]
```
[29:7:2023 - 13:54] [ERROR] | Error: connect ETIMEDOUT 2606:4700:3036::ac43:b2c7:2333
[29:7:2023 - 13:54] [ERROR] | [FATAL] Possibly Uncaught Exception
        Reason: ReferenceError: player is not defined

uncaughtException
[29:7:2023 - 13:57] [ERROR] | [FATAL] Possibly Unhandled Rejection
        Reason: RangeError: No available nodes.

Promise {
  <rejected> RangeError: No available nodes.
      at new Player (/Discord-MusicBot/djs-bot/node_modules/erela.js/dist/structures/Player.js:102:19)
      at new <anonymous> (/Discord-MusicBot/djs-bot/lib/clients/Erela.js:21:4)
      at ErelaExtended.create (/Discord-MusicBot/djs-bot/node_modules/erela.js/dist/structures/Manager.js:213:16)
      at ErelaExtended.createPlayer (/Discord-MusicBot/djs-bot/lib/clients/Erela.js:87:15)
      at SlashCommand.run (/Discord-MusicBot/djs-bot/commands/music/play.js:64:38)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
}
[29:7:2023 - 13:57] [ERROR] | [FATAL] Possibly Unhandled Rejection
        Reason: RangeError: No available nodes.

Promise {
  <rejected> RangeError: No available nodes.
      at new Player (/Discord-MusicBot/djs-bot/node_modules/erela.js/dist/structures/Player.js:102:19)
      at new <anonymous> (/Discord-MusicBot/djs-bot/lib/clients/Erela.js:21:4)
      at ErelaExtended.create (/Discord-MusicBot/djs-bot/node_modules/erela.js/dist/structures/Manager.js:213:16)
      at ErelaExtended.createPlayer (/Discord-MusicBot/djs-bot/lib/clients/Erela.js:87:15)
      at SlashCommand.run (/Discord-MusicBot/djs-bot/commands/music/play.js:64:38)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      ```

**Comment by BioCla** [comment]
Make sure your Lavalink configurations are correct and that the Lavalink process is actually running
